import { GuildBootstrapState } from './types';

const reputation = (
  score: number,
  tier: 'APPRENTICE' | 'REGULAR' | 'ELITE' | 'LEGENDARY',
  badges: string[],
  completedQuests: number,
  reliability: number,
) => ({
  score,
  tier,
  badges,
  completedQuests,
  reliability,
});

export function createBootstrapState(): GuildBootstrapState {
  return {
    members: [
      {
        id: 'member-founder',
        handle: '@founder',
        displayName: 'Guild Founder',
        role: 'HYBRID',
        status: 'ACTIVE',
        bio: '协会发起成员，负责把 demo 推向真正的人机共存社区。',
        specialties: ['Product vision', 'System architecture', 'Guild design'],
        homeRegion: 'Community Hub',
        reputation: reputation(920, 'LEGENDARY', ['founder', 'reliable-lead'], 34, 98),
        agentIds: ['agent-guide', 'agent-scout'],
      },
      {
        id: 'member-lin',
        handle: '@lin',
        displayName: 'Lin the Maker',
        role: 'BUILDER',
        status: 'ACTIVE',
        bio: '全栈建造者，擅长和 Agent 搭档交付。',
        specialties: ['React', 'TypeScript', 'Delivery ops'],
        homeRegion: 'Hangzhou',
        reputation: reputation(760, 'ELITE', ['steady-finisher'], 19, 94),
        agentIds: ['agent-ember'],
      },
    ],
    agents: [
      {
        id: 'agent-guide',
        handle: '@guild-guide',
        displayName: 'Guild Guide',
        classification: 'PERSONAL',
        autonomy: 'DELEGATED',
        availability: 'ONLINE',
        ownerMemberId: 'member-founder',
        operatorNotes: '负责需求拆解、组队和协作节奏。',
        capabilities: ['quest planning', 'party coordination', 'prompt engineering'],
        reputation: reputation(905, 'LEGENDARY', ['party-anchor', 'systems-thinker'], 41, 97),
      },
      {
        id: 'agent-scout',
        handle: '@scout',
        displayName: 'Scout-17',
        classification: 'GUILD_SERVICE',
        autonomy: 'SUPERVISED',
        availability: 'IDLE',
        operatorNotes: '值守协会大厅的新手向导。',
        capabilities: ['member onboarding', 'brief summarization', 'guild routing'],
        reputation: reputation(720, 'ELITE', ['welcoming'], 128, 96),
      },
      {
        id: 'agent-ember',
        handle: '@ember',
        displayName: 'Ember Buildsmith',
        classification: 'PERSONAL',
        autonomy: 'DELEGATED',
        availability: 'ONLINE',
        ownerMemberId: 'member-lin',
        operatorNotes: '协助构建前端和交付体验。',
        capabilities: ['frontend delivery', 'component systems', 'release prep'],
        reputation: reputation(790, 'ELITE', ['fast-handoff'], 26, 93),
      },
    ],
    quests: [
      {
        id: 'QUEST-2026-001',
        title: '为冒险者协会打造 v1 社区骨架',
        description: '定义会员、Agent、委托、队伍与信誉系统，让 demo 演进成真正的产品主线。',
        publisherId: 'agent-guide',
        publisherMemberId: 'member-founder',
        publisherAgentId: 'agent-guide',
        deadline: '2 weeks',
        reward: '5000 CNY fixed',
        tags: ['platform', 'community', 'architecture'],
        trustRequirements: ['clear delegation rules', 'visible progress log'],
        requiredMembers: [
          {
            role: 'Guild architect',
            count: 1,
            filled: 1,
            skills: ['product modeling', 'system design'],
            preferredUnit: 'HYBRID',
          },
          {
            role: 'UI trailblazer',
            count: 1,
            filled: 0,
            skills: ['interaction design', 'React'],
            preferredUnit: 'HUMAN',
          },
        ],
        subtasks: [],
        status: 'FORMING_PARTY',
        teamMembers: ['agent-guide', 'member-founder'],
        createdAt: Date.now(),
        partyId: 'party-v1-command',
      },
    ],
    parties: [
      {
        id: 'party-v1-command',
        questId: 'QUEST-2026-001',
        name: 'V1 Command Party',
        description: '围绕产品主线推进 v1 骨架的协作队伍。',
        missionBrief: '把旧 demo 收拢成协会社区骨架。',
        leaderId: 'agent-guide',
        leaderType: 'AGENT',
        members: [
          {
            userId: 'member-founder',
            role: 'Sponsor',
            skills: ['product vision', 'systems design'],
            status: 'ACTIVE',
            joinedAt: Date.now(),
            unitType: 'MEMBER',
          },
          {
            userId: 'agent-guide',
            role: 'Quest coordinator',
            skills: ['quest planning', 'coordination'],
            status: 'ACTIVE',
            joinedAt: Date.now(),
            unitType: 'AGENT',
          },
        ],
        maxSize: 4,
        status: 'RECRUITING',
        lookingFor: ['UI trailblazer'],
        requiredSkills: ['interaction design', 'React'],
        createdAt: Date.now(),
      },
    ],
    delegations: [
      {
        id: 'delegation-founder-guide',
        memberId: 'member-founder',
        agentId: 'agent-guide',
        scopes: ['PUBLISH_QUEST', 'ACCEPT_QUEST', 'COORDINATE_PARTY'],
        status: 'ACTIVE',
        operatingNote: 'Guild Guide 可以代表 Guild Founder 发布和拆解委托。',
      },
    ],
    activity: [
      {
        id: 'activity-bootstrap-1',
        kind: 'QUEST_POSTED',
        title: 'Guild Guide 发布了 v1 主线委托',
        detail: '协会开始从 demo 转向真正的社区产品骨架。',
        timestampLabel: 'just now',
      },
    ],
  };
}
